### ISSUE TITLE
Fix `timestamp_before` argument for `#get_messages_in_conversation` in readme

### ISSUE THREAD

**Issue by ydakuka** [crisp-im/ruby-crisp-api#13]
https://docs.crisp.chat/references/rest-api/v1/#get-messages-in-conversation

**Comment by ydakuka** [comment]
It has already been added.

```ruby
client.website.get_messages_in_conversation(
  website_id, session_id,
  {
    "timestamp_before" => timestamp_before.to_s,
  }
)
```

**Comment by baptistejamin** [comment]
Hi, our agents are offline at the moment. Please leave a message and we will get back to you as soon as possible.
