### ISSUE TITLE
New idea: "Get A Conversation" method contains neither the number of messages nor the number of pages

### ISSUE THREAD

**Issue by ydakuka** [crisp-im/ruby-crisp-api#16]
https://docs.crisp.chat/references/rest-api/v1/#get-a-conversation

**Comment by eliottvincent** [comment]
Hello there, can you please elaborate?

**Comment by ydakuka** [comment]
@eliottvincent it must be implemented on your side.

**Comment by eliottvincent** [comment]
I still don't understand :)

**Comment by ydakuka** [comment]
@eliottvincent  `GET /v1/website/{website_id}/conversation/{session_id}` request contains a lot of messages which I can get through `GET /v1/website/{website_id}/conversation/{session_id}/messages` request (with page_size = 20). I need to know how many messages exist?

**Comment by eliottvincent** [comment]
You can't know in advance the number of messages. When calling `/messages`:
* if you receive a 206 HTTP code, it means there are more messages (so you need to proceed to another `/messages` request)
* if you receive a 200 HTTP code, there are no more messages

You can see examples in our API ref: https://docs.crisp.chat/references/rest-api/v1/#get-messages-in-conversation

<img width="486" alt="Screen Shot 2023-07-04 at 13 04 56@2x" src="https://github.com/crisp-im/ruby-crisp-api/assets/24720375/eb915b63-af9e-493b-991c-9676f1523228">

**Comment by ydakuka** [comment]
> You can't know in advance the number of messages. When calling /messages:

Yes, you're right, but I want to know the number of messages when calling `GET /v1/website/{website_id}/conversation/{session_id}` using new useful field (e.g. `total_messages`).

**Comment by eliottvincent** [comment]
That is simply not possible and we have not planned to implement that, for now.
