### ISSUE TITLE
New idea: Add `page_size` query parameter

### ISSUE THREAD

**Issue by ydakuka** [crisp-im/ruby-crisp-api#18]
In order not to deal with [rate limits](https://docs.crisp.chat/guides/rest-api/rate-limits/), please add page_size query parameter (default, 20).

**Comment by eliottvincent** [comment]
Hello, we don't plan to implement this.

**Comment by ydakuka** [comment]
@eliottvincent okay, what are the rate limits? Could you please add more info to the developer guide? I don't know what timeout should I add when I make 1000000+ requests due to page_size = 20.

**Comment by eliottvincent** [comment]
We don't disclose our rate-limits, as they are dynamic and different according to every API route.

Just re-schedule your API calls when you hit a 422 or 429 HTTP response.

**Comment by ydakuka** [comment]
There's a headache here, but okay.
